version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/project
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/deploy_frontend.sh
  ValidateService:
    - location: scripts/deploy_backend.sh